import random

truths = [
    "What is your biggest fear?",
    "What is your biggest secret?",
    "Who was your first crush?",
    "What is your most embarrassing moment?",
    "Have you ever lied to your best friend?",
    "What is something you’re bad at but wish you were good at?",
    "What’s the weirdest dream you’ve ever had?",
    "Who do you like the most right now?",
    "What’s the last thing you searched on Google?",
    "Have you ever cheated in a test?",
    "What’s the one thing you regret the most?",
    "What’s your biggest insecurity?",
    "Have you ever been caught doing something you shouldn’t?",
    "What’s the strangest habit you have?",
    "What’s your guilty pleasure?",
    "Who is the last person you stalked on social media?",
    "Have you ever broken something and blamed someone else?",
    "What’s the biggest lie you’ve told?",
    "What’s something you’ve never told anyone?",
    "What’s your biggest flex?",
    "Who do you trust the most?",
    "What’s your biggest weakness?",
    "Have you ever cried during a movie?",
    "What’s your worst fear in relationships?",
    "What’s the most awkward conversation you’ve had?",
    "Have you ever had a crush on a teacher?",
    "What’s your most useless talent?",
    "What’s the silliest thing you’re afraid of?",
    "What’s your worst habit?",
    "Who is your secret best friend?",
    "Have you ever pretended to like something you hate?",
    "What’s the most trouble you’ve ever been in?",
    "What’s your biggest dream?",
    "What’s the weirdest thing you’ve eaten?",
    "What’s your biggest turn-off?",
    "Who knows you the best?",
    "Have you ever cried in public?",
    "What’s the biggest rumor you’ve heard about yourself?",
    "What’s something you wish you could change about yourself?",
    "What’s your biggest motivation?",
    "Who do you miss the most?",
    "What’s your favorite memory?",
    "What’s the worst decision you’ve made?",
    "Have you ever lied to your parents?",
    "What’s your biggest jealousy?",
    "Who do you admire the most?",
    "What’s the most childish thing you still do?",
    "What’s your biggest fear about the future?",
    "What’s one thing you’d never do even for money?",
    "What’s your biggest achievement?",
    "What’s your favorite song right now?",
    "Who was the last person who made you laugh?",
    "What’s something you’re proud of but never talk about?",
    "What’s your biggest pet peeve?",
    "Have you ever been in love?",
    "What’s the dumbest thing you’ve ever done?",
    "What’s the most expensive thing you’ve ever bought?",
    "What’s your dream job?",
    "What’s something you’re scared to tell people?",
    "Who is your role model?",
    "What’s the best compliment you’ve ever received?",
    "What’s your biggest fear about failing?",
    "What’s the weirdest talent you have?",
    "What’s your favorite childhood memory?",
    "What’s the worst lie you ever told?",
    "What’s something you want to learn this year?",
    "Who do you talk to when you’re sad?",
    "What’s your biggest distraction?",
    "What’s the last thing that made you cry?",
    "What’s your biggest motivation in life?",
    "What’s your favorite food?",
    "What’s your least favorite subject?",
    "Who do you look up to the most?",
    "What’s the most awkward thing you’ve ever said?",
    "What’s your biggest dream for the future?",
    "What’s something you’ve never done but want to try?",
    "What’s your favorite movie?",
    "What’s the last secret you kept?",
    "What’s your biggest fear about growing up?",
    "What’s something that always makes you smile?",
    "What’s your favorite holiday?",
    "What’s the last lie you told?",
    "What’s something you’re really bad at?",
    "What’s your favorite app?",
    "What’s your biggest challenge right now?",
    "What’s the most childish thing you still enjoy?",
    "What’s something you wish people knew about you?",
    "What’s your biggest dream in life?",
    "What’s the one thing you can’t live without?",
    "What’s the nicest thing someone has ever done for you?",
    "What’s your biggest weakness in relationships?",
    "What’s your favorite hobby?",
    "What’s the last thing you regretted doing?",
    "What’s your biggest fear about success?",
    "What’s something you want to change about your routine?"
]

dares = [
    "Do 10 push-ups",
    "Sing a song loudly",
    "Dance for 30 seconds",
    "Do your best animal impression",
    "Speak in a cartoon voice for one minute",
    "Send a funny emoji to someone",
    "Act like a robot for 30 seconds",
    "Do 15 jumping jacks",
    "Try to lick your elbow",
    "Say your name backwards",
    "Walk like a model for one minute",
    "Tell a joke right now",
    "Pretend you’re in a movie scene",
    "Do 20 squats",
    "Say the alphabet without moving your lips",
    "Make a funny face and hold it for 20 seconds",
    "Balance on one foot for 30 seconds",
    "Speak without using the letter A for one minute",
    "Do your best evil laugh",
    "Pretend to be your favorite celebrity",
    "Do 5 burpees",
    "Act like a baby for one minute",
    "Sing like a rockstar",
    "Do a slow-motion walk",
    "Say three nice things about yourself",
    "Pretend you’re a news reporter",
    "Do 25 jumping jacks",
    "Act like you’re underwater",
    "Speak in slow motion for one minute",
    "Pretend your phone is ringing and answer it",
    "Do 30 squats",
    "Act like a monkey",
    "Tell a scary story in 30 seconds",
    "Do 15 sit-ups",
    "Pretend you’re invisible",
    "Speak like a villain",
    "Do 40 jumping jacks",
    "Do your best superhero pose",
    "Act like you won the lottery",
    "Pretend you’re on a game show",
    "Do 20 lunges",
    "Make a beatbox sound",
    "Pretend to be a teacher",
    "Do your best zombie walk",
    "Say five animal names in five seconds",
    "Act like you’re on a red carpet",
    "Do 10 claps and 10 stomps",
    "Speak like a pirate",
    "Do a one-minute plank",
    "Take a deep bow like a king",
    "Talk in a whisper for one minute",
    "Walk backwards for 30 seconds",
    "Pretend to be a cat",
    "Do your best villain laugh",
    "Act like you’re on a runway",
    "Say the months of the year backwards",
    "Do five yoga poses",
    "Pretend you’re a superhero saving the world",
    "Do 20 high knees",
    "Talk like a baby for 30 seconds",
    "Act like you’re in a silent movie",
    "Do 15 toe touches",
    "Pretend you’re a famous YouTuber",
    "Do your best victory dance",
    "Say your favorite word ten times fast",
    "Walk like you’re stuck in slow motion",
    "Do 30 arm circles",
    "Pretend to be a chicken",
    "Tell a dramatic story",
    "Do 25 squats",
    "Act like a spy",
    "Do 20 push-ups against the wall",
    "Pretend you’re in a horror movie",
    "Do 10 sit-ups",
    "Make a silly noise every time you blink for 30 seconds",
    "Pretend to be a singer in a concert",
    "Do 15 jumping jacks with arms only",
    "Act like a video game character",
    "Do 30 seconds of shadow boxing",
    "Pretend to be a news anchor",
    "Do 20 calf raises",
    "Act like a cartoon character",
    "Do 10 burpees",
    "Pretend you’re in space",
    "Do 30 seconds wall sit",
    "Act like a magician",
    "Do 20 mountain climbers",
    "Pretend to be a DJ",
    "Do 30 seconds jumping in place",
    "Act like you’re stuck in an elevator",
    "Do 15 crunches",
    "Pretend to be a movie villain",
    "Do 20 jumping jacks with only legs",
    "Act like a zombie in slow motion"
]


print("\n🎯 Welcome to Truth & Dare Game!")
while True:
        choice = input("\nType 'truth', 'dare', or 'exit': ").lower()

        if choice == "truth":
            print("👉 Your Truth is:", random.choice(truths))

        elif choice == "dare":
            print("👉 Your Dare is:", random.choice(dares))

        elif choice == "exit":
            print("Exiting Truth & Dare 👋")
            break

        else:
            print("Invalid choice ❌ Try 'truth' or 'dare'")

             # 🔁 Play again question
        again = input("Play again? (yes/no): ").lower()
        if again != "yes":
            print("Exiting Rock Paper Scissor 👋")
            